### ISSUE TITLE
Configuration viewer

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#124]
Ability to see all configuration defined in an application, as a means of determining what can be overridden.

Quarkus has a config viewer, it might be possible to extract pieces from there for re-use.

Log the information during startup at an appropriate level.

**Comment by radcortez** [comment]
This can be done with the SmallRye Config LoggingInterceptor:
https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html#logging-interceptor
