### ISSUE TITLE
JUnit 5

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-parent#133]
I think it's time to go to JUnit 5. We can stay backward compatible with JUnit Vintage.

I'll suggest a PR.

This is a prerequisite for https://github.com/smallrye/smallrye-graphql/issues/100

**Comment by kenfinnigan** [comment]
I don't think Arquillian works with JUnit5 at present, which is a blocker as we need it for the TCKs.

Maybe one solution is to define both JUnit versions, as if I recall they're different artifacts

**Comment by t1** [comment]
Arquillian seems to work just fine with JUnit 5 Vintage. At least https://github.com/smallrye/smallrye-graphql/pull/216 builds just fine.

**Comment by kenfinnigan** [comment]
Good to know.

Before we change the parent I think it would be good to verify another project with a SNAPSHOT of the parent

**Comment by t1** [comment]
@kenfinnigan : I can do that. What project would you suggest?

**Comment by kenfinnigan** [comment]
Maybe smallrye-fault-tolerance?

**Comment by t1** [comment]
It works just fine with `smallrye-fault-tolerance`.

But truth be told, I've also tried it with `smallrye-reactive-messaging` as it's even more complex... and it fails with exceptions that I don't understand :-( I guess they'd have to manage their JUnit 4 dependency themselves until they find a workaround or a fix. But they already use JUnit 5 in some parts, so it's just a switch from managing the future to managing the past ;-)

**Comment by t1** [comment]
@kenfinnigan : ... or would you prefer two managed dependencies? If yes, we can either add `version.junit5` in addition to the existing `version.junit` (easier upgrade for existing projects) or a new `version.junit4` and update the exiting `version.junit` (more future proof).

**Comment by t1** [comment]
We would like to use JUnit 5 in smallrye-graphql. Can I help in any way?

**Comment by kenfinnigan** [comment]
Initially it's probably best to have both JUnit versions and dependencies in the pom.

**Comment by t1** [comment]
@radcortez just added it. I have a minor [comment on that](https://github.com/smallrye/smallrye-parent/commit/a0ede6d1c4012f87ed09e3c1a91f600b89ed3bea#r39533107). Then we can close this.
