### ISSUE TITLE
MultiRelease (MR) JAR support

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-parent#45]
The JBoss Parent POM project has had support for MR JARs for some time now.  This is consumed by downstream projects such as WildFly Common.  With WildFly Common's components moving piecewise to SmallRye, it would be greatly helpful to introduce these changes to the SmallRye parent project as well for general usage amongst SmallRye projects.

See also the [documentation](https://github.com/jboss/jboss-parent-pom#multi-release-jars) and [implementation](https://github.com/jboss/jboss-parent-pom/blob/master/pom.xml#L873-L1445) in the JBoss Parent POM project.

**Comment by kenfinnigan** [comment]
I think at present some projects do this directly, possibly FT and Context Propagation, but agree we should have it at the parent level for use by all
