### ISSUE TITLE
Update to Jakarta EE 8 dependencies

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#67]
Ensure all SmallRye implementations are using Jakarta EE 8 dependencies. This will require that Java EE 8 dependencies are excluded from the MicroProfile artifact dependencies.

Jakarta EE dependencies should be marked `provided`

**Comment by radcortez** [comment]
For current MicroProfile 3.2 releases (and used by Quarkus):

| Spec | MP version | SmallRye version  | javax transitive deps
--- | --- | --- | ---
| Config | 1.3 | 1.5.1 | No 
| Fault Tolerance | 2.0.3 | 4.0.0 | No
| Health | 2.1 | 2.1.0 | javax.inject via health api 2.1
| JWT | 1.1.1 | 2.0.12 | javax.annotations 
| Metrics | 2.2.1 | 2.3.3 | javax.inject via rest client api 1.3.4
| OpenAPI | 1.1.2 | 1.1.20 | No
| OpenTracing | 1.3.2 | 1.3.3 | No
| Rest Client | 1.3.4 | 4.4.2.Final (RestEasy) | javax.cdi, javax.el, javax.interceptor, javax.inject via smallrye config 1.3.9

**Comment by radcortez** [comment]
For next MicroProfile 3.3 releases:

| Spec | MP version | SmallRye version  | javax transitive deps
--- | --- | --- | ---
| Config | 1.4 | 1.6.0 | No 
| Fault Tolerance | 2.1 | 4.1.0-SNAPSHOT | No
| Health | 2.2 (2.2-RC3) | 2.1.1-SNAPSHOT | javax.inject, javax.cdi, javax.interceptor via health api 2.2-RC3
| JWT | 1.1.1 | 2.0.13 | No
| Metrics | 2.3 (2.3-RC2) | 2.4.0-SNAPSHOT | No
| OpenAPI | 1.1.2 | 1.1.21-SNAPSHOT | No
| OpenTracing | 1.3.2 | 1.3.4-SNAPSHOT | javax.inject via rest client api
| Rest Client | 1.4 (1.4-RC2) | 4.5.0-SNAPSHOT (RestEasy) | No

**Comment by kenfinnigan** [comment]
@antoinesd @xstefank can one of you ensure that SRye Health is using Jakarta EE and excludes any transitives for javax before a release?

@radcortez could you submit a PR for OpenTracing?

And thanks @radcortez for the investigation

**Comment by radcortez** [comment]
I can, I'm actually thinking in pushing a project to perform all of these validations automatically. I was trying to play with Maven Enforcer a bit, but it seems that the converge rule only works in transitive dependencies at the same level (so if you have any conflicts and it is resolver by maven transitive resolution rules, Enforcer will be happy)

Plus, since we know that MP API can do breaking changes, we may loose compatibility, so we may need to know that specs need to be updated.

SmallRye Health itself is using Jakarta, the issue is the MP Health API that is transitively including the javax dependencies.

**Comment by xstefank** [comment]
and we can't exclude them from the MP Health API as that would be considered a breaking change.

**Comment by radcortez** [comment]
Actually all of our current SmallRye masters are not transitively pushing any javax dependencies. These are being cause by issues in upstream libraries (MP Health API and MP Rest Client API).

**Comment by radcortez** [comment]
@xstefank but MP Health is moving from 2.1 to 2.2 (with a 2.3-RC3 now). Couldn't this be fixed over  there?

**Comment by xstefank** [comment]
@radcortez no, breaking change can only happen in a major release. We plan to move to Jakarta artifacts in June (MP 4.0).

However, can't we just exclude javax artifacts in smallrye and pull jakarta ones?

**Comment by radcortez** [comment]
@xstefank yes, that can be done at the SmallRye level. Just exclude the javax one coming from Health and use the jakarta ones. They shouldn't be transitively included anyway by SmallRye Health I believe.

**Comment by radcortez** [comment]
Actually, in MP Health, they don't need to be changed, just mark them as provided should work. I don't think that implementors rely on transitively getting the javax dependencies from Health.

**Comment by xstefank** [comment]
@radcortez still, even change to provided is considered a breaking change as users can also depend on the spec artifact directly. I can't find the discussion but this was discussed in the google group as part of MP 3.3 planning.

**Comment by kenfinnigan** [comment]
Yeah, the issue is that some MP specs didn't have javax dependencies as `provided`.

Fixing that means a breaking change, so it's postponed until MP 4.0

In the interim SRye projects need to exclude javax dependencies

**Comment by radcortez** [comment]
Ok. Sorry for pushing. Was not aware of that conversation :)

**Comment by radcortez** [comment]
Done for SmallRye Opentracing:
https://github.com/radcortez/smallrye-opentracing/commit/e0e749026288fd3e3aa22480afe0e887d1fc3896

**Comment by xstefank** [comment]
Health - https://github.com/smallrye/smallrye-health/pull/79

**Comment by radcortez** [comment]
Ok, we just need now the releases of SmallRye OpenTracing and Health.

**Comment by kenfinnigan** [comment]
Is OpenTracing good for a release?

Though they're `provided`, it looks like its still on Java EE dependencies.

**Comment by radcortez** [comment]
Yes, they are. I was looking into OpenTracing for most of the day to fix some of the issues. TCK was not running reliable, and the latest minor from MP also broke the TCK (and I believe it might break in Quarkus as well) due to https://github.com/eclipse/microprofile-opentracing/issues/184

There is https://github.com/smallrye/smallrye-opentracing/pull/98 which moves the dependencies to jakarta but states that requires MP OpenAPI 1.4. I'm having a look to see if we really need the MP OpenAPI release.

**Comment by radcortez** [comment]
I believe it should be good to go, but I want to give it a try on Quarkus first.

**Comment by kenfinnigan** [comment]
Any update @radcortez?

**Comment by radcortez** [comment]
Oh yes. I've released a version of Smallrye Open Tracing  and updated the version in Quarkus.

**Comment by radcortez** [comment]
Here is the Quarkus PR (already Merged):
https://github.com/quarkusio/quarkus/pull/7207

TCK is passing.

**Comment by kenfinnigan** [comment]
So good to close this then?

**Comment by radcortez** [comment]
I believe so.

**Comment by kenfinnigan** [comment]
Thanks
