### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#68]
- Site that aggregates the documentation from each project into a manageable piece
- Possibly utilize Antora to pull it together
- Skin it in same manor as main website

**Comment by kenfinnigan** [comment]
Ideally, all projects move to a pattern similar to https://github.com/smallrye/smallrye-reactive-messaging/tree/master/doc in that the documentation is just adoc files and images with no `pom.xml`

**Comment by kenfinnigan** [comment]
Priority on this should probably be raised, as it could be common documentation for WildFly, Quarkus, or anyone else to embed in their documentation.

Thoughts @paulrobinson

**Comment by jmartisk** [comment]
I am planning to write up some docs for Metrics soon, so I guess at the same time I could have a look at Antora or something for the unification

**Comment by paulrobinson** [comment]
@kenfinnigan are you saying that it's a strong requirement to have this done in a way that will make it easy for EAP and Quarkus to consume the docs? If so, understanding their processes is probably more important than investigating a solution that works for SmallRye in isolation.

**Comment by kenfinnigan** [comment]
Only in the sense that if we follow the doc modularization process, each chunk should be easily consumable by anything downstream

**Comment by paulrobinson** [comment]
Is this being considered by the Antora evaluation, or are these orthogonal requirements? CC @jmartisk

**Comment by kenfinnigan** [comment]
It's separate but related.

We need to be able to define docs in a modular fashion, and whatever tool we use to generate documentation needs to be able to collect all the pieces

**Comment by paulrobinson** [comment]
O, thanks.

Lets move this discussion over to the Antora discussion on the SR community mailing list.

**Comment by jmartisk** [comment]
First version of the new documentation is live, I suppose this can be closed, and potential improvements tracked in separate issues
