### ISSUE TITLE
Update to MP Config 1.4

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#75]
https://github.com/smallrye/smallrye-config/milestone/2

**Comment by kenfinnigan** [comment]
@dmlloyd @jmesnil do either of you happen to know what work is outstanding for supporting the MP Config spec that will be released?

If you don't that's fine, just wasn't sure

**Comment by dmlloyd** [comment]
Nothing formalized, but I think we want to get in as many doc clarifications as possible.

**Comment by radcortez** [comment]
Done.

https://github.com/smallrye/smallrye-config/pull/234
https://github.com/smallrye/smallrye-config/pull/233
