### ISSUE TITLE
Update to Fault Tolerance 2.1

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#76]
Not sure if the milestone would be 4.0.1 or 4.1.0?

**Comment by Ladicek** [comment]
I think we'll probably want to call it 4.1.

**Comment by kenfinnigan** [comment]
Thanks!

https://github.com/smallrye/smallrye-fault-tolerance/milestone/25

**Comment by kenfinnigan** [comment]
Is this done with the release of SRye FT 4.1?

**Comment by Ladicek** [comment]
Ah, correct!
