### ISSUE TITLE
Update to MP Health 2.2

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#77]
https://github.com/smallrye/smallrye-health/milestone/3

**Comment by kenfinnigan** [comment]
@antoinesd @xstefank what's the current status of this implementation?

Is it something Roberto could look at when he starts Wednesday?

**Comment by xstefank** [comment]
@kenfinnigan I have the implementation already ready locally passing the new TCK. So no need sorry.

**Comment by kenfinnigan** [comment]
No worries

**Comment by kenfinnigan** [comment]
@xstefank @antoinesd have we released the implementation?

**Comment by xstefank** [comment]
@antoinesd released it yesterday - https://github.com/smallrye/smallrye-health/releases/tag/2.2.0

**Comment by antoinesd** [comment]
Yes, it was released yesterday

**Comment by kenfinnigan** [comment]
Great, thanks!
