### ISSUE TITLE
Improved CI

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#79]
Investigate better CI options.

Not Travis, as they've had some issues around open source recently.

Semaphore 2 now offers free minutes for open source projects, previously it was 20 hrs free a month. But not sure if the random JVM crashes are "solved" with moving to v2.

Investigate GH Actions, maybe Azure.

See https://groups.google.com/forum/#!topic/smallrye/nGGA9MBdCT0 for some experiments @cescoffier has done with GH Actions

Things CI needs to do:
 - PR builds
 - Master builds
 - Push coverage to SonarCloud
 - Push documentation (general and javadoc)
 - Release project, with a specified version
 - Update website with project release

**Comment by kenfinnigan** [comment]
As part of this, we also need an automated release job for smallrye-parent repo

**Comment by radcortez** [comment]
I was looking a little bit into this, because I believe we should start adding support for running the TCK's with multiple JDK's (witch Semaphore does not support).

It seems that Github Actions could be a good candidate. 

I also had a very positive experience with https://drone.io. It allows you to set pipelines with multiple step, and each step runs in separate docker container using an image of your choice, so it very flexible it that regard.

**Comment by kenfinnigan** [comment]
I agree that we need to run all builds, including TCKs, on multiple JVMs. Clement started doing that with Reactive Messaging, as per his post.

I am leaning towards GH Actions, just because it's all bundled in one, but not wedded to that either. I think I also saw that GH Actions allows you to define a series of workflows in a separate git repo and then apply that to all repositories, which could be a very neat way to keep everything in sync across repos

**Comment by radcortez** [comment]
If you are ok with it, I can try to replicate and get some experience by applying Github Actions in MP Config.

**Comment by kenfinnigan** [comment]
That would be great.

Maybe provide some feedback to Clement's thread, or a new one, depending on what you find

**Comment by radcortez** [comment]
Sure!

**Comment by radcortez** [comment]
Proposal for new Build and Release process:
https://github.com/smallrye/smallrye-parent/wiki/SmallRye-Release-Process

Missing how to handle documentation. Discussion happening in the mailing list about adopting Antora.

**Comment by Ladicek** [comment]
Looking at https://github.com/radcortez/smallrye-config-release/blob/master/.github/workflows/release.yml and I don't see `mvn release:perform` anywhere. How is the release pushed to Central?

Also, `.github/release/version` seems a bit deep in the directory structure. Perhaps `.github/release-version`? If the file could contain a comment (e.g., ignore all lines starting with `#`?) about its purpose and usage, that would be nice too IMHO.

**Comment by cescoffier** [comment]
I know node is cool and so on, but committing the node_modules does not feel right. It makes repository big and updates tricky.
Any reason to not use KScript or JBang? At least it can resolve the dependencies on the fly.

**Comment by radcortez** [comment]
> Looking at https://github.com/radcortez/smallrye-config-release/blob/master/.github/workflows/release.yml and I don't see `mvn release:perform` anywhere. How is the release pushed to Central?

Ah, yes. It's missing that piece, because I didn't want to actually perform the release when I was trying out stuff. If we are happy with the current approach, I'll add the missing commands for gpg and perform in the release.yml.

> Also, `.github/release/version` seems a bit deep in the directory structure. Perhaps `.github/release-version`? If the file could contain a comment (e.g., ignore all lines starting with `#`?) about its purpose and usage, that would be nice too IMHO.

We can do that as well.

**Comment by radcortez** [comment]
> I know node is cool and so on, but committing the node_modules does not feel right. It makes repository big and updates tricky. Any reason to not use KScript or JBang? At least it can resolve the dependencies on the fly.
> […](#)

I probably like node as much as you do :)

There are only 2 ways to build your own Github Action, for you to reuse across workflows, either with Javascript Node or Docker:
https://help.github.com/en/actions/building-actions

I've ended up trying the Javascript Node approach, because most of the Actions that Github provides are done that way, include the setup-java.

Unfortunately, they require you to commit the node_modules directory:
https://help.github.com/en/actions/building-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Comment by kenfinnigan** [comment]
Is this sufficiently implemented to move to "Done" on the board?

**Comment by radcortez** [comment]
I believe so, but not every SmallRye project adopted it yet. Should we keep this open until everyone adopts this? Or we can consider the improvement done and the adoption a separate thing?

**Comment by kenfinnigan** [comment]
I think we can consider the process and improvement as done, it just needs each project to implement it
